filetype plugin indent on " Automatically detect file types.
inoremap jk <ESC>
set background=dark
colorscheme base16-tomorrow-night
set colorcolumn=120
set encoding=utf-8
set history=1000
set termguicolors         " fix green line numbers
set relativenumber
set showcmd               " Show (partial) command in status line.
set showmatch             " Show matching brackets.
syntax on

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif
