# Generated by bin/files/agent-routing-generate. Do not edit.
{
  profiles = {
    office = {
      claude = {
        agent_directory = "office";
        agents = [ "spawn-subagent-gather" "spawn-subagent-explore" "spawn-subagent-review" "spawn-subagent-implement" ];
        runtime = "office-claude";
            };
      codex = {
        agent_directory = "office";
        default = {
          effort = "xhigh";
          label = "luna";
          model = "gpt-6-luna";
          runtime = "office-codex";
          tier = "economy";
                };
        lead = {
          effort = "high";
          label = "sol";
          model = "gpt-6-sol";
          runtime = "office-codex";
          tier = "frontier";
                };
        opencode_go = false;
            };
      pi = {
        effort = "high";
        label = "sol";
        model = "gpt-6-sol";
        provider = "openai-codex";
        runtime = "office-codex";
        tier = "frontier";
            };
        };
    personal = {
      codex = {
        agent_directory = "personal";
        default = {
          effort = "xhigh";
          label = "deepseek";
          model = "deepseek-v4.1-flash";
          runtime = "personal-home";
          tier = "economy";
                };
        lead = {
          effort = "high";
          label = "mimo";
          model = "xiaomi/mimo-v2.6-pro";
          runtime = "personal-home";
          tier = "frontier";
                };
        opencode_go = true;
            };
      pi = {
        effort = "high";
        label = "sol";
        model = "gpt-6-sol";
        provider = "openai-codex";
        runtime = "office-codex";
        tier = "frontier";
            };
        };
    };
  runtimes = {
    office_claude = {
      default_tier = "economy";
      display_name = "Office Claude Code";
      opencode_go = false;
      provider = "claude";
      tiers = {
        balanced = {
          label = "opus";
          model = "opus";
                };
        economy = {
          label = "sonnet";
          model = "sonnet";
                };
        frontier = {
          label = "opus";
          model = "opus";
                };
            };
        };
    office_codex = {
      default_tier = "economy";
      display_name = "Office Codex";
      opencode_go = false;
      provider = "codex";
      tiers = {
        balanced = {
          label = "sol";
          model = "gpt-6-sol";
                };
        economy = {
          label = "luna";
          model = "gpt-6-luna";
                };
        frontier = {
          label = "sol";
          model = "gpt-6-sol";
                };
            };
        };
    personal_home = {
      default_tier = "economy";
      display_name = "Personal Codex home tiers";
      opencode_go = true;
      provider = "neutral";
      tiers = {
        balanced = {
          label = "deepseek-pro";
          model = "deepseek-v4-pro";
                };
        economy = {
          label = "deepseek";
          model = "deepseek-v4.1-flash";
                };
        frontier = {
          label = "mimo";
          model = "xiaomi/mimo-v2.6-pro";
                };
            };
        };
    };
  schema_version = 1;
}
