# Generated by bin/files/agent-routing-generate. Do not edit.
{
  profiles = {
    office = {
      codex = {
        agent_directory = "office";
        default = {
          effort = "xhigh";
          label = "luna";
          model = "gpt-6-luna";
          runtime = "office-codex";
          tier = "economy";
                };
        lead = {
          effort = "high";
          label = "sol";
          model = "gpt-6-sol";
          runtime = "office-codex";
          tier = "frontier";
                };
        opencode_go = false;
            };
      pi = {
        effort = "high";
        label = "sol";
        model = "gpt-6-sol";
        provider = "openai-codex";
        runtime = "office-codex";
        tier = "frontier";
            };
        };
    personal = {
      codex = {
        agent_directory = "personal";
        default = {
          effort = "xhigh";
          label = "deepseek";
          model = "deepseek-v4.1-flash";
          runtime = "personal-opencode-go";
          tier = "economy";
                };
        lead = {
          effort = "high";
          label = "deepseek";
          model = "deepseek-v4.1-flash";
          runtime = "personal-opencode-go";
          tier = "frontier";
                };
        opencode_go = true;
            };
      pi = {
        effort = "high";
        label = "sol";
        model = "gpt-6-sol";
        provider = "openai-codex";
        runtime = "office-codex";
        tier = "frontier";
            };
        };
    };
  runtimes = {
    office_codex = {
      default_tier = "economy";
      display_name = "Office Codex";
      opencode_go = false;
      provider = "codex";
      tiers = {
        balanced = {
          effective_efforts = [ "low" "medium" "high" "xhigh" "max" "ultra" ];
          label = "sol";
          model = "gpt-6-sol";
                };
        economy = {
          effective_efforts = [ "low" "medium" "high" "xhigh" "max" ];
          label = "luna";
          model = "gpt-6-luna";
                };
        frontier = {
          effective_efforts = [ "low" "medium" "high" "xhigh" "max" "ultra" ];
          label = "sol";
          model = "gpt-6-sol";
                };
            };
        };
    personal_opencode_go = {
      default_tier = "economy";
      display_name = "Personal Codex via OpenCode Go";
      opencode_go = true;
      provider = "codex";
      tiers = {
        balanced = {
          effective_efforts = [ "none" "low" "medium" "high" "xhigh" "max" "ultra" ];
          label = "deepseek";
          model = "deepseek-v4.1-flash";
                };
        economy = {
          effective_efforts = [ "none" "low" "medium" "high" "xhigh" "max" "ultra" ];
          label = "deepseek";
          model = "deepseek-v4.1-flash";
                };
        frontier = {
          effective_efforts = [ "none" "low" "medium" "high" "xhigh" "max" "ultra" ];
          label = "deepseek";
          model = "deepseek-v4.1-flash";
                };
            };
        };
    };
  schema_version = 1;
}
