file_opener = "cursor"
model = "gpt-5.4"
model_reasoning_effort = "medium"
model_verbosity = "medium"
notify = ["/bin/sh", "-c", "$HOME/dotfiles/bin/files/codex-notify.sh \"$1\"", "codex-notify"]
personality = "pragmatic"
approval_policy = "untrusted"
allow_login_shell = false
model_context_window = 1050000
model_auto_compact_token_limit = 800000

# sandbox_mode = "read-only"
sandbox_mode = "workspace-write"
suppress_unstable_features_warning = true
web_search = "cached"

# You can also add custom .tmTheme files under $CODEX_HOME/themes.
theme = "tokyo-night"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"

[agents]
max_threads = 10
max_depth = 1

[features]
multi_agent = true
prevent_idle_sleep = true
responses_websockets = false
responses_websockets_v2 = false
voice_transcription = true

[sandbox_workspace_write]
exclude_slash_tmp = false      # Allow /tmp
exclude_tmpdir_env_var = false # Allow $TMPDIR
network_access = false

[history]
persistence = "save-all"
max_bytes = 1073741824 # 1 GiB history cap

[tui]
animations = true
notification_method = "bel"
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-window-size", "used-tokens", "context-remaining", "context-used", "project-root"]
notifications = ["agent-turn-complete"]
theme = "tokyo-night"

[plugins."github@openai-curated"]
enabled = true

terminal_title = ["spinner", "project", "app-name", "status", "thread", "model", "task-progress"]

[mcp_servers.datadog-mcp]
enabled = false
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp"

[mcp_servers.glean_default]
url = "https://chime-prod-be.glean.com/mcp/default"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.slack]
url = "https://mcp.slack.com/mcp"

[plugins."slack@openai-curated"]
enabled = true
